pipeline {
    agent any

    stages {
        stage('Checkout Selected Folder from Git') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/deepbijwe/Jenkins-Projects.git'
                    ]],
                    extensions: [[
                        $class: 'SparseCheckoutPaths',
                        sparseCheckoutPaths: [[
                            path: 'k8s-Intergeration-Jenkins'
                        ]]
                    ]]
                ])
            }
        }

        stage('Verify') {
            steps {
                sh 'ls -l'
                sh 'ls -l k8s-Intergeration-Jenkins'
            }
        }


        stage ('deployement')
        {
            steps {
                sh 'kubectl apply -f k8s-Intergeration-Jenkins/deployment.yaml'
                sh 'kubectl apply -f k8s-Intergeration-Jenkins/service.yaml'
            }
        }

        stage ('check deployment status')
        {
            steps {
                sh 'kubectl get pods'
                sh 'kubectl get pods -o wide'
                sh 'kubectl get svc'
            }
        }
    }
}